- name: Install miniconda and dash services
  hosts: dask
  gather_facts: no
  roles:
    - dask-miniconda

- hosts: master
  tasks:
  - name: enable dscheduler
    become: yes
    service:
      name: dscheduler
      enabled: yes

- hosts: worker
  become: yes
  tasks:
  - name: enable dworker
    service:
      name: dworker
      enabled: yes

